image:
  repository: linuxserver/sonarr
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8989

env:
  - name: TZ
    value: "America/Toronto"
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

# /config directory must be available
wireguard: false

volumeMounts:
- mountPath: /config
  name: config
- mountPath: /downloads
  name: downloads
- mountPath: /data
  name: data
- mountPath: /data2
  name: data2
- mountPath: /cold
  name: cold

volumes:
- name: config
  hostPath:
    path: /data/configs/sonarr
    type: Directory
- name: downloads
  hostPath:
    path: /data/downloads
    type: Directory
- name: data
  hostPath:
    path: /data/tv
    type: Directory
- name: data2
  hostPath:
    path: /data2/tv
    type: Directory
- name: cold
  hostPath:
    path: /cold/tv
    type: Directory

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
