image:
  repository: linuxserver/radarr
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 7878

env:
  - name: TZ
    value: "America/Toronto"
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: PEERDNS
    value: "10.96.0.10"

# /config directory must be available
wireguard: false

volumeMounts:
- mountPath: /config
  name: config
- mountPath: /data
  name: data
- mountPath: /data2
  name: data2
- mountPath: /cold
  name: cold

volumes:
- name: config
  hostPath:
    path: /data/configs/radarr
    type: Directory
- name: data
  hostPath:
    path: /data/movies
    type: Directory
- name: data2
  hostPath:
    path: /data2/movies
    type: Directory
- name: cold
  hostPath:
    path: /cold/movies
    type: Directory

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
