image:
  repository: linuxserver/jackett
  pullPolicy: Always
  tag: "latest"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 9117

env:
  - name: TZ
    value: "America/Toronto"
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

# /config directory must be available
wireguard: true

volumeMounts:
  - mountPath: /config
    name: config

volumes:
  - name: config
    hostPath:
      path: /data/configs/jackett
      type: Directory

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
