image:
  repository: linuxserver/transmission
  pullPolicy: IfNotPresent
  tag: "amd64-3.00-r6-ls144"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 9091

env:
  - name: TZ
    value: "America/Toronto"
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

# /config directory must be available
wireguard: true

volumeMounts:
- mountPath: /config
  name: config
- mountPath: /downloads
  name: downloads
- mountPath: /watch
  name: watch

volumes:
- name: config
  hostPath:
    path: /data/configs/transmission
    type: Directory
- name: downloads
  hostPath:
    path: /data/downloads
    type: Directory
- name: watch
  emptyDir:
    sizeLimit: 500Mi

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

