apiVersion: v1
kind: Pod
metadata:
  name: wg
spec:
  # securityContext:
  #   sysctls:
  #   - name: net.ipv4.conf.all.src_valid_mark
  #     value: "1"
  containers:
  - name: wg
    image: linuxserver/wireguard:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_MODULE"]
    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
      - name: "TZ"
        value: "America/Toronto"
    volumeMounts:
    - mountPath: /config
      name: config
  volumes:
  - name: config
    hostPath:
      path: /data/configs/wireguard
      type: Directory

# 51820/udp port
